lsi: false
safe: true

source: .

title: "Transit Store - California Integrated Mobility"
description: Lorem Ipsum Dolor Sit Amet

baseurl: ""
url: https://cal-itp-transit-store.netlify.app

collections:
  categories:
    output: true
  products:
    output: true

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - docker-compose.yml
  - netlify.toml
  - README.md
  - submodules
