backend:
  name: git-gateway
  branch: master

media_folder: "assets/uploads"

collections:
  - name: "navigation"
    label: "Navigation"
    description: "The menus on the site."
    editor:
      preview: false
    files:
      - label: "Main navigation"
        name: "nav_main"
        file: "_data/nav_main.yml"
        fields:
          - label: "Navigation items"
            label_singular: "Navigation item"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {
                  label: "Open in",
                  name: "target",
                  widget: "select",
                  default: { label: "Same tab", value: "_self" },
                  options: [
                    { label: "Same tab", value: "_self" },
                    { label: "New tab", value: "_blank" }
                  ]
                }

      - label: "Footer navigation"
        name: "nav_footer"
        file: "_data/nav_footer.yml"
        fields:
          - label: "Navigation items"
            label_singular: "Navigation item"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {
                  label: "Open in",
                  name: "target",
                  widget: "select",
                  default: { label: "Same tab", value: "_self" },
                  options: [
                    { label: "Same tab", value: "_self" },
                    { label: "New tab", value: "_blank" }
                  ]
                }

  - name: "pages"
    label: "Pages"
    description: "Landing pages with unique layouts and options."
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/pages/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Social image", name: "image", widget: "image", hint: "Displayed in social shares and links." }
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "For browser tabs and social shares; combined with the site title."
            }
          - {label: "Headline", name: "headline", widget: "string"}
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              minimal: true,
              buttons: [
                bold,
                italic,
                link,
                bulleted-list,
                numbered-list
              ],
              editor_components: []
            }
          - {label: "Hero image", name: "hero_image", widget: "image" }
          - {
              label: "Primary Call to Action",
              name: "primary_action",
              widget: "relation",
              collection: "actions",
              value_field: "ref_id",
              search_fields: ["title", "text", "body"],
              display_fields: ["title"]
            }
          - {
              label: "Secondary Call to Action",
              name: "secondary_action",
              widget: "relation",
              collection: "actions",
              value_field: "ref_id",
              search_fields: ["title", "text", "body"],
              display_fields: ["title"]
            }
          - {
              label: "Final Call to Action",
              name: "final_action",
              widget: "relation",
              collection: "actions",
              value_field: "ref_id",
              search_fields: ["title", "text", "body"],
              display_fields: ["title"]
            }

      - label: "Providers"
        name: "providers"
        file: "content/pages/providers.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "providers"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Social image", name: "image", widget: "image", hint: "Displayed in social shares and links." }
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "For browser tabs and social shares; combined with the site title."
            }
          - {label: "Headline", name: "headline", widget: "string"}
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              minimal: true,
              buttons: [
                bold,
                italic,
                link,
                bulleted-list,
                numbered-list
              ],
              editor_components: []
            }
          - {
              label: "About the Data",
              name: "about",
              widget: "markdown",
              minimal: true,
              buttons: [
                bold,
                italic,
                link,
                heading-three,
                heading-four,
                heading-five,
                heading-six,
                bulleted-list,
                numbered-list
              ],
              editor_components: []
            }
          - {
              label: "Data action",
              name: "action",
              hint: "Select a Call to Action item to generate a button in the About section.",
              widget: "relation",
              collection: "actions",
              value_field: "ref_id",
              search_fields: ["title", "text", "body"],
              display_fields: ["title"]
            }
          - {
              label: "Source",
              name: "source",
              widget: "markdown",
              minimal: true,
              buttons: [
                bold,
                italic,
                link,
                heading-three,
                heading-four,
                heading-five,
                heading-six,
                bulleted-list,
                numbered-list
              ],
              editor_components: []
            }

      - label: "Subscribe"
        name: "subscribe"
        file: "content/pages/subscribe.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "form"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Social image", name: "image", widget: "image", hint: "Displayed in social shares and links." }
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "For browser tabs and social shares; combined with the site title."
            }
          - {label: "Headline", name: "headline", widget: "string"}
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              minimal: true,
              buttons: [
                bold,
                italic,
                link,
                bulleted-list,
                numbered-list
              ],
              editor_components: []
            }
          - {
              label: "Roles",
              label_singular: "role",
              name: "roles",
              widget: "list",
              summary: "{{fields.name}}",
              fields: [{
                label: "Name",
                name: "name",
                widget: "string"
              }]
            }
          - {
              label: "Areas of Interest",
              label_singular: "area",
              name: "areas",
              widget: "list",
              summary: "{{fields.name}}",
              fields: [
                {label: "Name", name: "name", widget: "string"},
                {label: "Description", name: "description", widget: "string"}
              ]
            }
          - {
              label: "Confirmation",
              name: "confirmation",
              widget: "object",
              summary: "{{fields.message}}",
              fields: [
                {
                  label: "Message",
                  name: "message",
                  widget: "markdown",
                  buttons: [
                    bold,
                    italic,
                    link,
                    heading-two,
                    heading-three,
                    heading-four,
                    heading-five,
                    heading-six,
                    bulleted-list,
                    numbered-list
                  ],
                  editor_components: [
                    "image",
                    "image-caption",
                    "pull-quote",
                    "youtube"
                  ]
                },
                {
                  label: "Button",
                  name: "action",
                  widget: "relation",
                  collection: "actions",
                  value_field: "ref_id",
                  search_fields: ["title", "text", "body"],
                  display_fields: ["title"]
                }
              ]
            }
          - {label: "Form include", name: "form", widget: "hidden"}

      - label: "Glossary"
        name: "glossary"
        file: "_data/glossary.yml"
        fields:
          - label: "Terms"
            label_singular: "Term"
            name: "items"
            widget: "list"
            summary: "{{fields.term}}"
            fields:
              - {label: "Term", name: "term", widget: "string"}
              - {label: "Definition", name: "definition", widget: "text"}

  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    description: "Used to create a grouping of other content items, such as Articles."
    editor:
      preview: false
    folder: "content/_categories"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "description", widget: "string", hint: "For cards and other summary displays"}
      - {label: "Header image", name: "header_image", widget: "image"}
      - {
          label: "Call to Action",
          name: "action",
          widget: "relation",
          collection: "actions",
          value_field: "ref_id",
          search_fields: ["title", "text", "body"],
          display_fields: ["title"]
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: [
            bold,
            italic,
            link,
            heading-two,
            heading-three,
            heading-four,
            heading-five,
            heading-six,
            bulleted-list,
            numbered-list
          ],
          editor_components: [
            "image",
            "image-caption"
          ]
        }
      - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}

  - name: "posts"
    label: "Articles"
    label_singular: "Article"
    description: "Short and long-form content with a publish date and author."
    folder: "content/_posts"
    sort: "date:desc"
    create: true
    editor:
      preview: false
    preview_path: "/blog/{{year}}/{{month}}/{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Publish date",
          name: "date",
          widget: "datetime",
          hint: "Publish date is captured in UTC but displays in Pacific",
          date_format: "LL",
          time_format: false,
          picker_utc: true
        }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widet: "string", required: false}
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "metadata",
          file: "authors",
          search_fields: ["items.*.first_name", "items.*.last_name"],
          display_fields: ["items.*.first_name", "items.*.last_name"],
          value_field: "items.*.ref_id"
        }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          value_field: "ref_id",
          search_fields: ["title", "text", "body"],
          display_fields: ["title"]
        }
      - {label: "Summary", name: "description", widget: "string", hint: "Used for card, Social Media, and other summary displays"}
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: [
            bold,
            italic,
            link,
            heading-two,
            heading-three,
            heading-four,
            heading-five,
            heading-six,
            bulleted-list,
            numbered-list
          ],
          editor_components: [
            "image",
            "image-caption",
            "pull-quote",
            "youtube"
          ]
        }
      - {
          label: "Call to Action",
          name: "action",
          required: false,
          widget: "relation",
          collection: "actions",
          value_field: "ref_id",
          search_fields: ["title", "text", "body"],
          display_fields: ["title"]
        }
      - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}

  - name: "actions"
    label: "Calls to Action"
    label_singular: "Call to Action"
    description: "Reusable pieces of content that generate buttons and other clickable elements."
    editor:
      preview: false
    folder: "content/_actions"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Action text", name: "text", widget: "string", hint: "Used for action buttons"}
      - {label: "Action URL", name: "href", widget: "string"}
      - {
          label: "Open in",
          name: "target",
          widget: "select",
          default: { label: "Same tab", value: "_self" },
          options: [
            { label: "Same tab", value: "_self" },
            { label: "New tab", value: "_blank" }
          ]
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          minimal: true,
          buttons: [
            bold,
            italic
          ],
          editor_components: []
        }
      - {label: "Tile image", name: "tile_image", widget: "image", required: false, hint: "Used when this action is displayed as a tile."}
      - {label: "Card image", name: "card_image", widget: "image", required: false, hint: "Used when this action is displayed as a card."}
      - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}

  - name: "metadata"
    label: "Metadata"
    description: "Supporting content and configuration for the site."
    editor:
      preview: false
    files:
      - label: "Authors"
        name: "authors"
        file: "_data/authors.yml"
        fields:
          - label: "Authors"
            label_singular: "Author"
            name: "items"
            widget: "list"
            fields:
              - {label: "First name", name: "first_name", widget: "string"}
              - {label: "Last name", name: "last_name", widget: "string"}
              - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}

      - label: "Site Metadata"
        name: "meta"
        file: "_data/meta.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", hint: "Visible in the browser tab and in social share links."}
          - {label: "Description", name: "description", widget: "text", hint: "Visible in social share links for the site homepage and as a default for pages."}
          - {label: "Social image", name: "image", widget: "image", hint: "Default image for social share links (pages can override)."}