backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "assets/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "categories"
    label: "Category" # Used in the UI, ie.: "New Category"
    folder: "content/_categories" # The path to the folder where the documents are stored
    create: true # Do not allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "products" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Product" # Used in the UI, ie.: "New Product"
    folder: "content/_products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{category}}/{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "category"
        valueField: "name"
        searchFields: ["title", "name", "body"]
        displayFields: ["title"]

  - name: "config"
    label: "Configuration"
    editor:
      preview: false
    files:
      - label: "Footer navigation"
        name: "nav_footer"
        file: "_data/nav_footer.yml"
        fields:
          - label: "Navigation items"
            label_singular: "Navigation item"
            name: "items"
            widget: "list"
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Url, name: url, widget: string}