backend:
  name: git-gateway
  branch: master

media_folder: "assets/uploads"

collections:
  - name: "navigation"
    label: "Navigation"
    editor:
      preview: false
    files:
      - label: "Main navigation"
        name: "nav_main"
        file: "_data/nav_main.yml"
        fields:
          - label: "Navigation items"
            label_singular: "Navigation item"
            name: "items"
            widget: "list"
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Url, name: url, widget: string}

      - label: "Footer navigation"
        name: "nav_footer"
        file: "_data/nav_footer.yml"
        fields:
          - label: "Navigation items"
            label_singular: "Navigation item"
            name: "items"
            widget: "list"
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Url, name: url, widget: string}

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "For browser tabs and social shares; combined with the site title."
            }
          - {label: "Headline", name: "headline", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown", minimal: true}
          - {
              label: "Primary Call to Action",
              name: "primary_action",
              widget: "relation",
              collection: "actions",
              valueField: "ref_id",
              searchFields: ["title", "text", "body"],
              displayFields: ["title"]
            }
          - {
              label: "Secondary Call to Action",
              name: "secondary_action",
              widget: "relation",
              collection: "actions",
              valueField: "ref_id",
              searchFields: ["title", "text", "body"],
              displayFields: ["title"]
            }
          - {
              label: "Features",
              name: "features",
              widget: "relation",
              multiple: true,
              collection: "categories",
              valueField: "ref_id",
              searchFields: ["title", "text", "body"],
              displayFields: ["title"]
            }
          - {
              label: "Final Call to Action",
              name: "final_action",
              widget: "relation",
              collection: "actions",
              valueField: "ref_id",
              searchFields: ["title", "text", "body"],
              displayFields: ["title"]
            }

  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "content/_categories"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "description", widget: "string", hint: "For cards and other summary displays"}
      - {label: "Header graphic", name: "header_graphic", widget: "image"}
      - {
          label: "Call to Action",
          name: "action",
          widget: "relation",
          collection: "actions",
          valueField: "ref_id",
          searchFields: ["title", "text", "body"],
          displayFields: ["title"]
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          editorComponents: ["image"]
        }
      - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}

  - name: "posts"
    label: "Articles"
    label_singular: "Article"
    folder: "content/_posts"
    sort: "date:desc"
    create: true
    editor:
      preview: false
    preview_path: "/blog/{{year}}/{{month}}/{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Publish date",
          name: "date",
          widget: "datetime",
          hint: "Publish date is captured in UTC but displays in Pacific",
          dateFormat: "LL",
          timeFormat: false,
          pickerUtc: true
        }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widet: "string", required: false}
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "metadata",
          file: "authors",
          searchFields: ["items.*.first_name", "items.*.last_name"],
          displayFields: ["items.*.first_name", "items.*.last_name"],
          valueField: "items.*.ref_id"
        }
      - {label: "Summary", name: "description", widget: "string", hint: "Used for card, Social Media, and other summary displays"}
      - {
          label: Body,
          name: body,
          widget: markdown,
          buttons: [
            bold,
            italic,
            link,
            heading-two,
            heading-three,
            heading-four,
            heading-five,
            heading-six,
            quote,
            bulleted-list,
            numbered-list
          ],
          editorComponents: [image]
        }
      - {
          label: "Call to Action",
          name: "action",
          required: false,
          widget: "relation",
          collection: "actions",
          valueField: "ref_id",
          searchFields: ["title", "text", "body"],
          displayFields: ["title"]
        }
      - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}

  - name: "actions"
    label: "Calls to Action"
    label_singular: "Call to Action"
    folder: "content/_actions"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Action text", name: "text", widget: "string"}
      - {label: "Action URL", name: "href", widget: "string"}
      - {
          label: "Open in",
          name: "target",
          widget: "select",
          default: { label: "Same tab", value: "_self" },
          options: [
            { label: "Same tab", value: "_self" },
            { label: "New tab", value: "_blank" }
          ]
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          minimal: true,
          required: false,
          editorComponents: ["image"]
        }
      - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}

  - name: "metadata"
    label: "Metadata"
    editor:
      preview: false
    files:
      - label: "Authors"
        name: "authors"
        file: "_data/authors.yml"
        fields:
          - label: "Authors"
            label_singular: "Author"
            name: "items"
            widget: "list"
            fields:
              - {label: First name, name: first_name, widget: string}
              - {label: Last name, name: last_name, widget: string}
              - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}
