backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "assets/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "actions"
    label: "Calls to Action"
    label_singular: "Call to Action"
    folder: "content/_actions"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Action text", name: "text", widget: "string"}
      - {label: "Action URL", name: "url", widget: "string"}
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
        editorComponents: ["image"]

  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "content/_categories"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Header graphic", name: "header_graphic", widget: "image"}
      - label: "Call to Action"
        name: "action"
        widget: "relation"
        collection: "actions"
        valueField: "title"
        searchFields: ["title", "text", "body"]
        displayFields: ["title"]
      - label: "Body"
        name: "body"
        widget: "markdown"
        editorComponents: ["image"]

  - name: "products" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Product" # Used in the UI, ie.: "New Product"
    folder: "content/_products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{category}}/{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "category"
        valueField: "name"
        searchFields: ["title", "name", "body"]
        displayFields: ["title"]

  - name: "navigation"
    label: "Navigation"
    editor:
      preview: false
    files:
      - label: "Main navigation"
        name: "nav_main"
        file: "_data/nav_main.yml"
        fields:
          - label: "Navigation items"
            label_singular: "Navigation item"
            name: "items"
            widget: "list"
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Url, name: url, widget: string}

      - label: "Footer navigation"
        name: "nav_footer"
        file: "_data/nav_footer.yml"
        fields:
          - label: "Navigation items"
            label_singular: "Navigation item"
            name: "items"
            widget: "list"
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Url, name: url, widget: string}